export const FETCH_GAMES_STARTED = 'FETCH_GAMES_STARTED';
export const FETCH_GAMES_SUCCEEDED = 'FETCH_GAMES_SUCCEEDED';
export const FETCH_GAMES_FAILED = 'FETCH_GAMES_FAILED';
export const SHOW_GAME_DETAILS = 'SHOW_GAME_DETAILS';
export const SEARCH_GAMES = 'SEARCH_GAMES';
export const FILTER_GAMES = 'FILTER_GAMES';
export const SORT_GAMES = 'SORT_GAMES';
